version: '3.8'

services:
  web:
    container_name: backend
    build: .
    env_file:
      - ./app/.env
    environment:
      - PORT=8080
    ports:
      - "8000:8080"
    depends_on:
      - redis
  redis:
    container_name: backend_redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
